# Language-related config settings for parse_configuration_file tests

lang.ruby.filemask \.rb$
lang.ruby.bangmask ruby

lang.ruby.indent.size 2
lang.ruby.indent.auto true
lang.ruby.indent.roundup false
lang.ruby.indent.using_tabs false

lang.ruby.indent.indenters ^(def|class|module|if|else)\b
lang.ruby.indent.unindenters ^(end|else)\b
lang.ruby.indent.indenters_next_line (\bdo\b|\{)\s*$
lang.ruby.indent.triggers ^(end|else|rescue|ensure)\b

lang.ruby.indent.ignore ^#
lang.ruby.indent.preventers ^=begin
lang.ruby.context.ignore ^#

lang.ruby.tokens.comment ^#.*$
lang.ruby.tokens.string.open "
lang.ruby.tokens.string.close "
lang.ruby.tokens.keyword.case_insensitive (def|class|module|end)\b

lang.ruby.comment_string #

# Column markers
view.column_markers.standard.column 80
